# Generated by Django 5.1.15 on 2026-07-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.SlugField(max_length=120, unique=True)),
                ('property_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('asset_type', models.CharField(blank=True, default='', max_length=60)),
                ('nrsf', models.FloatField(blank=True, null=True)),
                ('acreage', models.FloatField(blank=True, null=True)),
                ('asking_price', models.FloatField(blank=True, null=True)),
                ('estimated_fair_value', models.FloatField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, default='N/A', max_length=40)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('deal_dir', models.CharField(blank=True, default='', max_length=500)),
                ('memo_filename', models.CharField(blank=True, default='', max_length=300)),
                ('excel_filename', models.CharField(blank=True, default='', max_length=300)),
                ('input_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-analysis_date', '-created_at'],
            },
        ),
    ]
