# Generated by Django 5.1.15 on 2026-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='assumption_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='cim_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='extract_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deal',
            name='extract_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='extract_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='extract_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='extraction_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
