# Generated by Django 5.1.15 on 2026-07-27 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_deal_assumption_overrides_deal_cim_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='running', max_length=10)),
                ('progress_step', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(default=9)),
                ('progress_msg', models.CharField(blank=True, default='', max_length=200)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('memo_filename', models.CharField(blank=True, default='', max_length=300)),
                ('excel_filename', models.CharField(blank=True, default='', max_length=300)),
                ('template_filename', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='webapp.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
