# Generated by Django 5.1.15 on 2026-07-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_analysisrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('value', models.JSONField()),
                ('asset_type', models.CharField(blank=True, default='', max_length=60)),
                ('effective_date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key', 'asset_type', '-effective_date', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='applied_overrides',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
