# Generated by Django 5.1.15 on 2026-07-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_configoverride_analysisrun_applied_overrides'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': [models.OrderBy(models.F('analysis_date'), descending=True, nulls_last=True), '-created_at']},
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_id',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
