# Generated by Django 5.1.15 on 2026-08-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_deal_options_alter_deal_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='investor_summary_filename',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
