# Generated by Django 5.1.15 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_analysisrun_investor_summary_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='portfolio_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='portfolio_suspect',
            field=models.BooleanField(default=False),
        ),
    ]
