# Generated by Django 5.1.15 on 2026-08-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_deal_portfolio_suspect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='enrichment_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
