# Generated by Django 5.1.15 on 2026-08-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    """Persist which tier supplied each demographic, beside the values.

    `null=True` and NOT `default=dict`, deliberately. After this runs, `{}`
    means "enrichment ran and had nothing to say" while NULL means "this Deal
    was extracted before the column existed" — and the second set is exactly
    the rows whose Census-measured populations keep rendering as "stated in
    the CIM", because the extract-time log they needed was discarded and is
    unrecoverable. Backfilling a default here would erase that distinction on
    the one day it can still be observed.
    """

    dependencies = [
        ('webapp', '0007_deal_portfolio_suspect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='enrichment_source_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
